### ISSUE TITLE
Minor rendering issues

### ISSUE THREAD

**Issue by fralau** [markmap/mkdocs-markmap#51]
Thanks for this interesting plugin!  I am @fralau,  the [maintainer of the mermaid2 plugin](https://github.com/fralau/mkdocs-mermaid2-plugin/tree/master). I believe that the idea of using markdown to represent mindmaps is sensible, and that the concept appears more mature than Mermaid minmaps!

Since it worked out of the box 👍 , I threw the [whole demo diagram from markmap.js.org](https://markmap.js.org/repl) at it.  It also worked immediately, so 👍  again!

Just a minor issue, the inline code is printed vertically:

```markdown
 - `inline code`
 ```
![markmap](https://github.com/markmap/mkdocs-markmap/assets/36767124/7add4c9f-dfcd-4f39-b78b-2861703ec598)

(I also appreciated that it works directly with pymdownx.superfences, out of the box).

**Comment by fralau** [comment]
As a side note, I tested the same diagram with Material, including with dark mode, and it doesn't give the same issue.
![markmap2](https://github.com/markmap/mkdocs-markmap/assets/36767124/58dc15e9-ada3-470f-b5c4-4b8156ccfc06)

The code block is slightly squashed, but this is also a minor issue.

It also works perfectly with Mermaid2, which is a side bonus.

```yaml
site_name: My Docs

theme: 
  # name: readthedocs
  name: material
  language: en
  palette:
    scheme: slate
    primary: red
    accent: pink

markdown_extensions:
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search
  - markmap
  - mermaid2:
      version: '10.1.0'
```

**Comment by fralau** [comment]
It also works perfectly with Mermaid2, which is a side bonus.

```yaml
site_name: My Docs

theme: 
  # name: readthedocs
  name: material
  language: en
  palette:
    scheme: slate
    primary: red
    accent: pink

markdown_extensions:
  - pymdownx.superfences:
        # make exceptions to highlighting of code:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid_custom

plugins:
  - search
  - markmap
  - mermaid2:
      version: '10.1.0'
```

![markmap3](https://github.com/markmap/mkdocs-markmap/assets/36767124/7028636d-1360-44b0-9169-4a9d8cc346f9)

Here is the Mermaid code:

````
```mermaid
graph LR
    hello --> world
    world --> again
    again --> hello
```
````
