### ISSUE TITLE
Asking for an update, it hasn't been updated for more than one year

### ISSUE THREAD

**Issue by jaywhj** [markmap/mkdocs-markmap#61]
Hello, Ask for updates, especially the markmap inside. 🙏

**Comment by neatc0der** [comment]
Hi there,

sure, I can do in update before year's end to bring all javascript components up to date. But, please have a look at the [readme](https://github.com/markmap/mkdocs-markmap?tab=readme-ov-file#advanced-settings). You can easily select the necessary markup version yourself:

```yaml
plugins:
  - markmap:
      lib_version: 0.17.0
      view_version: 0.17.0
```

Cheers!
